-- 코드를 입력하세요
SELECT R_INFO.REST_ID, R_INFO.REST_NAME, R_INFO.FOOD_TYPE, R_INFO.FAVORITES, R_INFO.ADDRESS, 
ROUND(AVG(R_REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO R_INFO, REST_REVIEW R_REVIEW
WHERE R_INFO.REST_ID = R_REVIEW.REST_ID 
GROUP BY R_INFO.REST_ID
HAVING R_INFO.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, R_INFO.FAVORITES DESC

