# -- 코드를 입력하세요
# SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN,'N') # IFNULL(FREEZER_YN,'N')
# FROM FOOD_WAREHOUSE 
# WHERE ADDRESS LIKE "경기도%"
# ORDER BY WAREHOUSE_ID ASC


# select WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN,'N')
select WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN,'N')
from FOOD_WAREHOUSE
where ADDRESS LIKE '경기도%'
order by WAREHOUSE_ID asc;