-- 코드를 입력하세요
# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_OUTS A
# WHERE A.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS WHERE ANIMAL_ID IS NOT NULL)
# ORDER BY A.ANIMAL_ID;

SELECT AOUT.ANIMAL_ID, AOUT.NAME
FROM ANIMAL_OUTS AOUT
LEFT JOIN ANIMAL_INS AIN
  ON AOUT.ANIMAL_ID = AIN.ANIMAL_ID
WHERE AIN.ANIMAL_ID IS NULL
ORDER BY AOUT.ANIMAL_ID;
