-- 코드를 작성해주세요
# SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM DEVELOPERS D, SKILLCODES S
# WHERE (S.CODE & D.SKILL_CODE) > 0
#     AND S.NAME IN ('Python', 'C#')
# ORDER BY ID ASC

select distinct D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
from DEVELOPERS D, SKILLCODES S
where (D.SKILL_CODE & S.CODE)  > 0
    and S.NAME in ('Python','C#')
order by D.ID asc;