-- 코드를 작성해주세요
SELECT SUM(GR.SCORE) AS SCORE, GR.EMP_NO, EM.EMP_NAME, EM.POSITION, EM.EMAIL
FROM HR_EMPLOYEES EM
    INNER JOIN HR_GRADE GR ON EM.EMP_NO = GR.EMP_NO
WHERE GR.YEAR = '2022'
GROUP BY GR.EMP_NO
ORDER BY SCORE DESC
LIMIT 1