# -- 코드를 입력하세요
# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
# WHERE B.BOARD_ID = R.BOARD_ID
#     AND YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
# ORDER BY R.CREATED_DATE ASC, B.TITLE ASC

# USED_GOODS_BOARD의 CREATED_DATE 이게 2022년 10월인 애들
# USED_GOODS_REPLY의 CREATED_DATE를 order by asc;
# 이게같다면 USED_GOODS_BOARD의 TITLE order by asc;
select 
    B.TITLE,
    B.BOARD_ID, 
    R.REPLY_ID, 
    R.WRITER_ID, 
    R.CONTENTS, 
    date_format(R.CREATED_DATE,"%Y-%m-%d")
from USED_GOODS_BOARD B
join USED_GOODS_REPLY R
on R.BOARD_ID = B.BOARD_ID
where YEAR(B.CREATED_DATE) = 2022 
and MONTH(B.CREATED_DATE) = 10
order by R.CREATED_DATE asc, B.TITLE asc;