# -- 코드를 입력하세요
# SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK B, AUTHOR A
# WHERE B.AUTHOR_ID = A.AUTHOR_ID
#     AND B.CATEGORY = '경제'
# ORDER BY B.PUBLISHED_DATE ASC









select B.BOOK_ID, A.AUTHOR_NAME, date_format(B.PUBLISHED_DATE,'%Y-%m-%d')
from BOOK B, AUTHOR A
where B.AUTHOR_ID = A.AUTHOR_ID
and B.CATEGORY = '경제'
order by B.PUBLISHED_DATE asc;